spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: lab-service-route
          uri: http://localhost:9090
          predicates:
            - Path=/lab-service/**

        - id: report-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/report-service/**

      